"""
Django settings for KN_practice project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import redis

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3qe98w3b2dr%t@!7+u*)#t%2e5=rgudhj@-s79szo^ne=qxrj0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'deduplicator',
]


REDIS_HOST = os.getenv('REDIS_HOST', 'localhost')
REDIS_PORT = int(os.getenv('REDIS_PORT', 6379))
REDIS_DB = int(os.getenv('REDIS_DB_DEDUP', 0))

DEDUPLICATOR_TTL_SECONDS = int(os.getenv('DEDUPLICATOR_TTL_SECONDS', 60))

DEDUPLICATOR_KEY_FIELDS = [
    'event_name',
    'userId',
    'client_id',
    'product_id',
    'content_id',
    'channel_id',
]

REDIS_INSTANCE = None
EVENT_DEDUPLICATOR_INSTANCE = None

try:
    REDIS_INSTANCE = redis.Redis(host=REDIS_HOST, port=REDIS_PORT, db=REDIS_DB, decode_responses=True)
    REDIS_INSTANCE.ping()
    print(f"Успешное подключение к Redis: {REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}")
    from deduplicator.logic import EventDeduplicator

    try:
        EVENT_DEDUPLICATOR_INSTANCE = EventDeduplicator(
            redis_client=REDIS_INSTANCE,
            ttl_seconds=DEDUPLICATOR_TTL_SECONDS,
            key_fields=DEDUPLICATOR_KEY_FIELDS
        )
        print("Инстанс EventDeduplicator успешно создан.")
    except ValueError as e:
        print(f"Ошибка конфигурации EventDeduplicator: {e}")
except redis.RedisError as e:
    print(f"Ошибка подключения к Redis: {e}")
    REDIS_INSTANCE = None

# Создаем инстанс дедупликатора
if REDIS_INSTANCE:
    try:
        EVENT_DEDUPLICATOR_INSTANCE = EventDeduplicator(
            redis_client=REDIS_INSTANCE,
            ttl_seconds=DEDUPLICATOR_TTL_SECONDS,
            key_fields=DEDUPLICATOR_KEY_FIELDS
        )
        print("Инстанс EventDeduplicator успешно создан.")
    except ValueError as e:
         print(f"Ошибка конфигурации EventDeduplicator: {e}")
         EVENT_DEDUPLICATOR_INSTANCE = None
else:
    EVENT_DEDUPLICATOR_INSTANCE = None

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'KN_practice.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'KN_practice.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
